version: "3.9"

services:
  wordpress-5.7.1-db:
    image: mariadb:10.3
    volumes:
      - /home/wnghks7787/WebSec/cms_crawler/docker_compose_builder/initial_page_builder/compose_files/wordpress-5.7.1/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password_root
      MYSQL_DATABASE: db-wordpress-5.7.1
      MYSQL_USER: user
      MYSQL_PASSWORD: password_user
    ports:
      - "3450:3306"

  wordpress-5.7.1:
    depends_on:
      - wordpress-5.7.1-db
    image: wordpress:5.7.1
    volumes:
      - /home/wnghks7787/WebSec/cms_crawler/docker_compose_builder/initial_page_builder/compose_files/wordpress-5.7.1/var/www/html
    restart: always
    environment:
      WORDPRESS_DB_HOST: wordpress-5.7.1-db:3306
      WORDPRESS_DB_USER: user
      WORDPRESS_DB_PASSWORD: password_user
      WORDPRESS_DB_NAME: db-wordpress-5.7.1
    ports:
      - "10050:80"
