version: "3.9"

services:
  drupal-9.0.7-db:
    image: mariadb:10.6
    volumes:
      - /home/wnghks7787/WebSec/cms_crawler/docker_compose_builder/initial_page_builder/compose_files/drupal-9.0.7/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password_root
      MYSQL_DATABASE: db-drupal-9.0.7
      MYSQL_USER: user
      MYSQL_PASSWORD: password_user
    ports:
      - "3725:3306"

  drupal-9.0.7:
    depends_on:
      - drupal-9.0.7-db
    image: drupal:9.0.7
    volumes:
      - /home/wnghks7787/WebSec/cms_crawler/docker_compose_builder/initial_page_builder/compose_files/drupal-9.0.7/var/www/html
    restart: always
    environment:
      DRUPAL_DB_HOST: drupal-9.0.7-db:3306
      DRUPAL_DB_USER: user
      DRUPAL_DB_PASSWORD: password_user
      DRUPAL_DB_NAME: db-drupal-9.0.7
    ports:
      - "10325:80"
