version: "3.9"

services:
  drupal-7.98-db:
    image: mariadb:10.6
    volumes:
      - /home/wnghks7787/WebSec/cms_crawler/docker_compose_builder/initial_page_builder/compose_files/drupal-7.98/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password_root
      MYSQL_DATABASE: db-drupal-7.98
      MYSQL_USER: user
      MYSQL_PASSWORD: password_user
    ports:
      - "3861:3306"

  drupal-7.98:
    depends_on:
      - drupal-7.98-db
    image: drupal:7.98
    volumes:
      - /home/wnghks7787/WebSec/cms_crawler/docker_compose_builder/initial_page_builder/compose_files/drupal-7.98/var/www/html
    restart: always
    environment:
      DRUPAL_DB_HOST: drupal-7.98-db:3306
      DRUPAL_DB_USER: user
      DRUPAL_DB_PASSWORD: password_user
      DRUPAL_DB_NAME: db-drupal-7.98
    ports:
      - "10461:80"
