version: "3.9"

services:
  joomla-4.0.2-db:
    image: mariadb:10.4
    volumes:
      - /home/wnghks7787/WebSec/cms_crawler/docker_compose_builder/initial_page_builder/compose_files/joomla-4.0.2/var/lib/mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: password_root
      MYSQL_DATABASE: db-joomla-4.0.2
      MYSQL_USER: user
      MYSQL_PASSWORD: password_user
    ports:
      - "3573:3306"

  joomla-4.0.2:
    depends_on:
      - joomla-4.0.2-db
    image: joomla:4.0.2
    volumes:
      - /home/wnghks7787/WebSec/cms_crawler/docker_compose_builder/initial_page_builder/compose_files/joomla-4.0.2/var/www/html
    restart: always
    environment:
      JOOMLA_DB_HOST: joomla-4.0.2-db:3306
      JOOMLA_DB_USER: user
      JOOMLA_DB_PASSWORD: password_user
      JOOMLA_DB_NAME: db-joomla-4.0.2
    ports:
      - "10173:80"
